[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#05070d"
secondaryBackgroundColor = "#0d1220"
textColor = "#f5f7fb"
font = "sans serif"